
// cargaExcelModelDet.js

module.exports = (sequelize, type) => {
	return sequelize.define('orq_carga_excel_det',{
		id:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: true
		},
		uu_id : type.STRING,
		Codigo : type.STRING,
		CodigoHead: type.STRING,
		Token : type.STRING,
        Indice: type.INTEGER,

		Col01 : type.STRING,
        Col02 : type.STRING,
        Col03 : type.STRING,
        Col04 : type.STRING,
        Col05 : type.STRING,
        Col06 : type.STRING,
        Col07 : type.STRING,
        Col08 : type.STRING,
        Col09 : type.STRING,
        Col10 : type.STRING,
        Col11 : type.STRING,
        Col12 : type.STRING,
        Col13 : type.STRING,
        Col14 : type.STRING,
        Col15 : type.STRING,
        Col16 : type.STRING,
        Col17 : type.STRING,
        Col18 : type.STRING,
        Col19 : type.STRING,
        Col20 : type.STRING,
        Col21 : type.STRING,
        Col22 : type.STRING,
        Col23 : type.STRING,
        Col24 : type.STRING,
        Col25 : type.STRING,
        Col26 : type.STRING,
        Col27 : type.STRING,
        Col28 : type.STRING,
        Col29 : type.STRING,
        Col30 : type.STRING,
        Col31 : type.STRING,
        Col32 : type.STRING,
        Col33 : type.STRING,
        Col34 : type.STRING,
        Col35 : type.STRING,
        Col36 : type.STRING,
        Col37 : type.STRING,
        Col38 : type.STRING,
        Col39 : type.STRING,
        Col40 : type.STRING,
        Col41 : type.STRING,
        Col42 : type.STRING,
        Col43 : type.STRING,
        Col44 : type.STRING,
        Col45 : type.STRING,
        Col46 : type.STRING,
        Col47 : type.STRING,
        Col48 : type.STRING,
        Col49 : type.STRING,
        Col50 : type.STRING,
        Col51 : type.STRING,
        Col52 : type.STRING,
        Col53 : type.STRING,
        Col54 : type.STRING,
        Col55 : type.STRING,
        Col56 : type.STRING,
        Col57 : type.STRING,
        Col58 : type.STRING,
        Col59 : type.STRING,
        Col60 : type.STRING,

		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}
