// constSuperModel
module.exports = (sequelize, type) => {
	return sequelize.define('orq_constancia_supervision',{
		id : {
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: true
		},
        Codigo                      : type.STRING, 
        uu_id                       : type.STRING,                       
        correlativo                 : type.INTEGER,
        cronograma                  : type.STRING,
        id_cronograma               : type.INTEGER,
        id_cliente                  : type.INTEGER,
        cliente                     : type.STRING,
        id_local                    : type.INTEGER,
        local                       : type.STRING,
        direccion                   : type.STRING,
        Distrito                    : type.STRING,
        nombre_contacto_cliente     : type.STRING,
        id_adsAcargo                : type.INTEGER,
        adsAcargo                   : type.STRING,
        fecha                       : type.DATE,
        personal_destacado          : type.STRING,
        nombre_jefegrupo            : type.STRING,
        nro_super_manana            : type.INTEGER,
        nro_super_tarde             : type.INTEGER,
        nro_super_noche             : type.INTEGER,
        personal_cubrir             : type.STRING,
        nro_personal_cubrir         : type.INTEGER,
        cronograma_cumple           : type.STRING,
        cronograma_detalle          : type.STRING,
        sshh_estado                 : type.STRING,
        oficinas_estado             : type.STRING,
        pisos_estado                : type.STRING,
        paredes_estado              : type.STRING,
        lunas_estado                : type.STRING,
        alfombra_estado             : type.STRING,
        mobiliario_estado           : type.STRING,
        sshh_comentario             : type.STRING,
        oficinas_comentario         : type.STRING,
        pisos_comentario            : type.STRING,
        paredes_comentario          : type.STRING,
        lunas_comentario            : type.STRING,
        alfombra_comentario         : type.STRING,
        mobiliario_comentario       : type.STRING,
        cant_material_faltante      : type.INTEGER,
        detalle_material_faltante   : type.STRING,
        cant_material_sobrante      : type.INTEGER,
        detalle_material_sobrante   : type.STRING,
        manubrio_estado             : type.STRING,
        ruedas_estado               : type.STRING,
        tapa_estado                 : type.STRING,
        cable_estado                : type.STRING,
        enchufe_estado              : type.STRING,
        nroplaca_aspiradoras        : type.STRING,
        detalle_aspiradoras         : type.STRING,
        nroplaca_lustradoras        : type.STRING,
        detalle_lustradoras         : type.STRING,
        presentacion_personal       : type.STRING,
        detalle_presentacion_personal: type.STRING,
        reclamo_cliente             : type.STRING,
        obs_complementarias         : type.STRING,
        firma_cliente               : type.STRING,
        puntuaje                    : type.DECIMAL(20,4),
        feedback                    : type.STRING,
        firma_ads_supervisor        : type.STRING,
        lat_creador                 : type.STRING,
        lng_creador                 : type.STRING,
        lat_califica                : type.STRING,
        lng_califica                : type.STRING,
        estado                      : type.STRING,
        id_usuario_aprueba          : type.INTEGER,
        UsuarioModAp                : type.STRING,
        FechaModAp                  : type.DATE,
        fecha_aprobado              : type.DATE,
        UsuarioModAn                : type.STRING,
        FechaModAn                  : type.DATE,
        IdUsuarioModAp              : type.INTEGER,
        MotivoAnulacion             : type.STRING,
        id_usuarioCreador           : type.INTEGER,
        usuarioCreador              : type.STRING,
        lat                         : type.STRING,
        lng                         : type.STRING,
        id_user_cerrado             : type.INTEGER,
        user_cerrado                : type.STRING,
        lat_cerrado                 : type.STRING,
        lng_cerrado                 : type.STRING,
        id_empresa_cerrado          : type.INTEGER,
        empresa_cerrado             : type.STRING,
        fecha_cerrado               : type.DATE,
        Adjuntos                    : type.STRING,
        url_pdf                     : type.STRING,
        id_empresa                  : type.INTEGER,
        empresa                     : type.STRING,


        deleted_at  : type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}