// docVentasCab231.js

module.exports = (sequelize, type) => {
	return sequelize.define('utb_docventaselec',{
		Correlativo:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: true
		},
        Serie : type.STRING,
        TVenta : type.STRING,
        IdClienteProv : type.BIGINT,
        nombre_cliente : type.STRING,
        Direccion : type.TEXT,
        FechaEmision : type.DATEONLY,
        FechaMySQL : type.DATEONLY,
        Vencimiento : type.DATEONLY,
        IdTipoPago : type.INTEGER,
        nombre_tipopago : type.STRING,
        NroGuia : type.STRING,
        NroCertificado : type.STRING,
        IdMoneda : type.INTEGER,
        
        SubTotalSolesPrev : type.DECIMAL(20,4),
        IGVSolesPrev    : type.DECIMAL(20,4),
        TotalSolesPrev  : type.DECIMAL(20,4),
        SubTotalDolares : type.DECIMAL(20,4),
        IGVDolares      : type.DECIMAL(20,4),
        TotalDolares    : type.DECIMAL(20,4),
        LetrasTotal     : type.TEXT,
        TipoCambio : type.DECIMAL(20,4),
        TipoDocOrigen : type.STRING,
        NroDocOrigen : type.STRING,
        IncIGV : type.INTEGER,
        Glosa : type.TEXT,
        UnidadNegocio : type.STRING,
        RepComercial : type.STRING,
        nombre_repcomercial : type.STRING,
        TipoDocumento : type.STRING,
        IdCuenta : type.INTEGER,
        nombre_cuenta : type.STRING,
        MotivoAnulacion : type.TEXT,
        Estado : type.STRING,
        UsuarioMod : type.INTEGER,
        FechaMod : type.DATE,
        MigradoCOBORD : type.STRING,
        EstadoCobro : type.TEXT,
        FechaVencimiento : type.DATE,
        IdResumenBaja : type.STRING,
        IdResumenBoleta : type.STRING,
        IdResumenBoletaBaja : type.STRING,
        C035 : type.INTEGER,
        C036 : type.DECIMAL(20,4),
        UsuarioModAnulado : type.STRING,
        C038 : type.INTEGER,
        FechaAnulado : type.DATE,
        bmigrado : type.STRING,
        C041 : type.DATE,
        C042 : type.STRING,
        C043 : type.STRING,
        C044 : type.STRING,
        C045 : type.STRING,
        IdSintetico : type.INTEGER,
        C047 : type.STRING,
        C048 : type.STRING,
        C049 : type.STRING,
        C050 : type.STRING,
        C051 : type.STRING,
        C052 : type.STRING,
        C053 : type.STRING,
        C054 : type.STRING,
        C055 : type.STRING,
        IGVPorcentaje : type.INTEGER,
        SubTotalDoc : type.DECIMAL(20,4),
        IGVDoc      : type.DECIMAL(20,4),
        TotalDoc    : type.DECIMAL(20,4),
        SubTotalSoles : type.DECIMAL(20,4),
        IGVSoles    : type.DECIMAL(20,4),
        TotalSoles  : type.DECIMAL(20,4),
        C056    : type.DECIMAL(20,4),
        C057    : type.DECIMAL(20,4),
        EstadoEmision : type.INTEGER,
        TipoDisposicion : type.INTEGER,
        Banco : type.INTEGER,
        NroCuenta : type.STRING,
        Moneda : type.STRING,
        ChequeA : type.STRING,
        ImporteDet : type.DECIMAL(20,4),
        FechaSint : type.STRING,
        NroSintetico : type.STRING,
        TipoDocumentoSint : type.STRING,
        Banco2 : type.STRING,
        EstadoSintetico : type.STRING,
        Banco3 : type.STRING,
        DirEnv : type.STRING,
        ContEnv : type.STRING,
        ContEnv : type.STRING,
        NotaFac1 : type.STRING,
        ReqFacOS : type.STRING,
        Urbanizacion : type.STRING,
        idUbigeo : type.INTEGER,
        emailCliente : type.STRING,
        NotaDEtalleFac : type.STRING,
        DesGlobal : type.STRING,
        idCatalogo7 : type.INTEGER,
        nombre_catalogo7 : type.STRING,
        NotaBancos : type.STRING,
        docAfectado : type.STRING,
        TipoDocAfectado : type.STRING,
        MotivoAfectado : type.TEXT,
        SerieNumero : type.STRING,
        TextoAuxiliar100_1 : type.STRING,
        TextoAuxiliar100_2 : type.STRING,
        TextoAuxiliar100_3 : type.STRING,
        Usuemisor : type.STRING,
        Autorizaciones : type.STRING,
        ordenCompra : type.STRING,
        hes : type.STRING,
        CodCC : type.STRING,
        id_empresa : type.STRING,
        empresa : type.STRING,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}

