// fichaPersonalModel.js
module.exports = (sequelize, type) => {
	return sequelize.define('orq_ficha_personal',{
		id:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: true
		},
        uu_id         : type.STRING,
		IdReqPersonal   : type.INTEGER,
		id_cliente      : type.INTEGER,
		cliente         : type.STRING,
        id_sucursal     : type.INTEGER,
        sucursal        : type.STRING,
        id_usuario_empleado : type.INTEGER,
        nombres          : type.STRING,
        NombreU          : type.STRING,
        ApellidoPaterno  : type.STRING,
        ApellidoMaterno  : type.STRING,
        Sexo             : type.STRING,
        motivo_req       : type.STRING,
        fecha_entrevista : type.DATEONLY,
        dni         : type.STRING,
        puesto      : type.STRING,
        id_puesto   : type.INTEGER,
        fuente      : type.STRING,
        unidad_local        : type.STRING,
        num_requerimiento   : type.INTEGER,
        turno_elegido   : type.STRING,
        disponibilidad  : type.STRING,
        inicio_contrato : type.DATEONLY,
        fin_contrato    : type.DATEONLY,
        sueldo              : type.DECIMAL(10, 2),
        asignacion_familiar : type.STRING,
        contrato            : type.STRING,
        fotocheck           : type.STRING,
        sctr                : type.STRING,
        cta_haberes         : type.STRING,
        curriculum          : type.STRING,
        certificado_policial : type.STRING,
        recibo_luz_agua     : type.STRING,
        copia_dni           : type.STRING,
        carnet_sanidad      : type.STRING,
        antecedentes        : type.STRING,
        verificativa        : type.STRING,
        pendientes          : type.STRING,
        pendientes_descripcion  : type.STRING,
        direccion_actual        : type.STRING,
        distrito                : type.STRING,
        referencia_domicilio : type.STRING,
        tipo_vivienda       : type.STRING,
        email               : type.STRING,
        fecha_nacimiento    : type.STRING,
        edad                : type.STRING,
        lugar_nacimiento    : type.STRING,
        estado_civil        : type.STRING,
        num_hijos   : type.STRING,
        telefono    : type.STRING,
        celular     : type.STRING,
        primaria    : type.STRING,
        secundario  : type.STRING,
        tecnico         : type.STRING,
        universitario   : type.STRING,
        carrera     : type.STRING,
        indice      : type.STRING,
        polo_camisa : type.STRING,
        pantalon    : type.STRING,
        calzado     : type.STRING,
        otros       : type.STRING,
        empresa_1   : type.STRING,
        empresa_2   : type.STRING,
        empresa_3   : type.STRING,
        cargop_1    : type.STRING,
        cargop_2    : type.STRING,
        cargop_3    : type.STRING,
        periodo_trabajo_1   : type.STRING,
        periodo_trabajo_2   : type.STRING,
        periodo_trabajo_3   : type.STRING,
        relaciones_inter    : type.STRING,
        adaptatibilidad : type.STRING,
        madurez_mental  : type.STRING,
        honestidad      : type.STRING,
        motivacion      : type.STRING,
        modales         : type.STRING,
        plan_organizacion   : type.STRING,
        analisis_problemas  : type.STRING,
        orienta_resultados  : type.STRING,
        compresion_instruc  : type.STRING,
        iniciativa      : type.STRING,
        sociabilidad    : type.STRING,
        tolerancia      : type.STRING,
        capacidad_obs   : type.STRING,
        comunica_asertiva   : type.STRING,
        liderazgo           : type.STRING,
        entrevista          : type.STRING,
        resultado_eva_psico : type.STRING,
        nombre_psicologo         : type.STRING,
        observacion_indu_capa    : type.STRING,
        nota_teorica_tecnica     : type.STRING,
        nota_practica_tecnica    : type.STRING,
        nota_induccion_seguridad : type.STRING,
        responsable     : type.STRING,
        token           : type.STRING,
        id_incidencia   : type.STRING,
        id_responsable_proceso  : type.STRING,
        responsable_proceso     : type.STRING,
        motivo      : type.STRING,
        id_usuario  : type.STRING,
        usuario_mod : type.STRING,
        envio_emo       : type.STRING,
        estado_ficha    : type.STRING,
        fecha_cubierto  : type.STRING,
        motivo_baja : type.STRING,
        texto_baja  : type.STRING,
        visible     : type.STRING,
        avatar      : type.STRING,
        avatar_40   : type.STRING,
        avatar_400  : type.STRING,
        deleted_at  : type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}