// fichainspModel

module.exports = (sequelize, type) => {
	return sequelize.define('utb_fichainspeccion',{
		idFichaInspeccion:{
			type          : type.INTEGER,
			primaryKey    : true,
			autoIncrement : true
        },
        uu_id           : type.STRING,
        Codigo          : type.STRING,
        numpropuesta1   : type.STRING,
        NroPte          : type.INTEGER,
		montopropuesta1 : type.DECIMAL(10, 6),
        moneda1         : type.STRING,
        condicion1      : type.STRING,
        numpropuesta2   : type.STRING,
        montopropuesta2 : type.DECIMAL(10, 6),
        moneda2         : type.STRING,
        condicion2      : type.STRING,
        numpropuesta3   : type.STRING,
        montopropuesta3 : type.DECIMAL(10, 6),
        moneda3         : type.STRING,
        condicion3      : type.STRING,
        numpropuesta4   : type.STRING,
        montopropuesta4 : type.DECIMAL(10, 6),
        moneda4         : type.STRING,
        condicion4      : type.STRING,
        numpropuesta5   : type.STRING,
        montopropuesta5 : type.DECIMAL(10, 6),
        moneda5         : type.STRING,
        condicion5      : type.STRING,
        fechahorainicio : type.DATE,
        fechahorafin    : type.DATE,
        DocCliente      : type.STRING,
        TipoDocumento   : type.STRING,
        TipoCliente     : type.STRING,
        UnidadNegocio   : type.STRING,
        NomCliente      : type.STRING,
        NomComercial    : type.STRING,
        DireccionFiscal : type.STRING,
        lat     : type.STRING,
        lng     : type.STRING,
        Urbanizacion    : type.STRING,
        Ubigeo          : type.STRING,
        ubigeo_texto    : type.STRING,
        idGiro          : type.STRING,
        giro            : type.STRING,
        Anexo           : type.STRING,
        Movil           : type.STRING,
        Departamento    : type.STRING,
        Provincia       : type.STRING,
        Distrito        : type.STRING,
        TipoDir         : type.STRING,
        NombreCalle     : type.STRING,
        NroCalle        : type.STRING,
        OtrosCalle      : type.STRING,
        DireccionServicio   : type.STRING,
        ReferenciaServicio  : type.STRING,
        NomSolicitante      : type.STRING,
        EmailSolicitante    : type.STRING,
        TelefonoSolicitante : type.STRING,
        AnexoSolicitante    : type.STRING,
        MovilSolicitante    : type.STRING,
        FechaServicio       : type.DATEONLY,
        HoraServicio        : type.STRING,
        Glosa               : type.STRING,
        FechaHoraContacto   : type.DATE,
        FormaContactoInicial: type.STRING,
        GlosaFormaContactoInicial: type.STRING,
        RepComercial            : type.INTEGER,
        NombreRepComercial      : type.STRING,
        UsuarioMod          : type.STRING,
        FechaMod            : type.DATE,
        Estado              : type.STRING,
        MedioAtencion       : type.STRING,
        ReqVisita           : type.STRING,
        usuario_comercial   : type.STRING,
        id_user_aprob       : type.INTEGER,
        fecha_aprob         : type.DATE,
        usuario_aprob       : type.STRING,
        id_empresa          : type.INTEGER,
        empresa             : type.STRING,
        id_centro_costo     : type.INTEGER,
        centrocosto         : type.STRING,
        correo_facturar     : type.STRING,
		deleted_at : type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}
