// guiaRemisionModel.js

module.exports = (sequelize, type) => {
	return sequelize.define('utb_guiaremisioncab',{
		IdGuiaCab:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: true
		},
		Serie 		: type.INTEGER,
		uu_id 		: type.STRING,
		IdClienteProv 	: type.DOUBLE,
		nombre_cliente 	: type.STRING,
		IdSucursal 		: type.INTEGER,
		FFFFsucursalFF 	: type.STRING,
		FechaEmision 	: type.DATEONLY,
		FechaTraslado 	: type.DATEONLY,
		MotivoTraslado 	: type.TEXT,
		nombre_motivo 	: type.STRING,
		IdCentro 		: type.INTEGER,
		centro_costo 	: type.STRING,
		Solicitante 	: type.TEXT,
		nombre_solicitante : type.STRING,
		Atencion 	: type.INTEGER,
		Glosa 		: type.TEXT,
		PesoNeto 	: type.STRING,
		IdTransportista 	 : type.TEXT,
		nombre_transportista : type.STRING,
		DirPartida 			 : type.TEXT,
		DirLlegada 			 : type.TEXT,
		AtencionAlmacenes 	 : type.INTEGER,
		IdAlmacenRecepcion 	 : type.INTEGER,
		almacen_recepcion 	 : type.STRING,
		C017 	: type.TEXT,
		C018 	: type.STRING,
		C019 	: type.INTEGER,
		C020 	: type.TEXT,
		C021 	: type.DECIMAL(10, 6),
		C022 	: type.INTEGER,
		C023 	: type.INTEGER,
		C024 	: type.TEXT,
		Estado 	: type.STRING,
		C026 	: type.DECIMAL(10, 6),
		C027 	: type.DECIMAL(10, 6),
		C028 	: type.DECIMAL(10, 6),
		C029 	: type.DECIMAL(10, 6),
		C030 	: type.DECIMAL(10, 6),
		C031 	: type.DECIMAL(10, 6),
		C032 	: type.TEXT,
		C033 	: type.TEXT,
		C034 	: type.TEXT,
		C035 	: type.TEXT,
		C036 	: type.TEXT,
		C037 	: type.STRING,
		UsuarioAprob : type.STRING,
		FechaMod 	 : type.DATE,
		UsuarioMod   : type.STRING,
		DocDevuelto  : type.STRING,
		C042 		 : type.TEXT,
		C043 		 : type.TEXT,
		C044 		 : type.TEXT,
		C045 		 : type.TEXT,
		C046 		 : type.TEXT,
		NroRequerimiento : type.TEXT,
		C048 		 : type.TEXT,
		C049 		 : type.TEXT,
		C050 		 : type.TEXT,
		C051 		 : type.TEXT,
		C052 		 : type.TEXT,
		C053 		 : type.TEXT,
		C054 		 : type.TEXT,
		C055 		 : type.TEXT,
		C056 		 : type.TEXT,
		C057 		 : type.TEXT,
		C058 		 : type.TEXT,
		C059 		 : type.TEXT,
		C060 		 : type.TEXT,
		TipoDocOrigen 	: type.STRING,
		NroDocOrigen 	: type.STRING,
		TipoGuia 		: type.STRING,
		items_detalle 	: type.DECIMAL(10, 6),
		items_req 		: type.DECIMAL(10, 6),
		total_cantidad 	: type.DECIMAL(10, 6),
		IdAlmacen 		: type.INTEGER,
		almacen 		: type.STRING,
		placa 			: type.STRING,
		nombre_placa 	: type.STRING,
		marca 			: type.STRING,
		IdConductor 	: type.STRING,
		conductor 		: type.STRING,
		licencia 		: type.STRING,
		despacho 		: type.INTEGER,
		id_empresa 		: type.INTEGER,
		empresa 		: type.STRING,
		deleted_at 		: type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}

