// osModel.js

module.exports = (sequelize, type) => {
	return sequelize.define('utb_ordenservicio',{
		IdOS:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: false
		},
		IdOT 		: type.INTEGER,
		Anexo 		: type.INTEGER,
		Fecha 		: type.STRING,
		FechaMySQL 	: type.DATEONLY,
		FechaHoraServicio: type.DATE,
		RepComercial : type.INTEGER,
		nombre_RepComercial : type.STRING,
		IdClienteProv 	: type.DOUBLE,
		nombre_cliente 	: type.STRING,
		IdLocal 	: type.INTEGER,
		local 		: type.STRING,
		Direccion 	: type.TEXT,
		IdGiro 		: type.INTEGER,
		giro 		: type.STRING,
		Precio 		: type.DECIMAL(10, 6),
		IncIGV 		: type.INTEGER,
		Indicador 	: type.INTEGER,
		TipoComprobante : type.INTEGER,
		IGVPorcentaje 	: type.INTEGER,
		TipoCambio 		: type.DECIMAL(10, 6),
		NroOC 		: type.TEXT,
		Medida 		: type.TEXT,
		Duracion 	: type.TEXT,
		Descripcion 	: type.TEXT,
		Referencia 		: type.TEXT,
		Solicitante 	: type.TEXT,
		IncCertificado 	: type.INTEGER,
		NroCertificado 	: type.TEXT,
		Glosa 			: type.TEXT,
		IdFrecuencia 	: type.INTEGER,
		Hora 			: type.INTEGER,
		TipoDocOrigen 	: type.TEXT,
		NroDocOrigen 	: type.TEXT,
		UsuarioMod 		: type.INTEGER,
		NombreUsuarioMod : type.STRING,
		UsuarioModAP 	: type.STRING,
		FechaModAP 		: type.DATE,
		UsuarioModAN : type.STRING,
		FechaModAN 	: type.DATE,
		MotivoAN 	: type.TEXT,
		FechaMod 	: type.DATE,
		IdMoneda 	: type.INTEGER,
		MotivoAnulacion : type.TEXT,
		IncDocVenta 	: type.INTEGER,
		Facturado 		: type.STRING,
		CondicionVenta 	: type.INTEGER,
		nombre_condicionventa : type.STRING,
		NroRecibo 		: type.TEXT,
		NroBoleta 		: type.TEXT,
		NroFactura 		: type.TEXT,
		ClaseServicio 	: type.STRING,// Contrato, Servicio
		NotaFact 	: type.TEXT,
		C040 		: type.INTEGER,
		C041 		: type.INTEGER,
		TotalSoles 	: type.DECIMAL(10, 6),
		SubTotalSoles : type.DECIMAL(10, 6),
		IGVSoles 	: type.DECIMAL(10, 6),
		TotalDoc 	: type.DECIMAL(10, 6),
		SubTotalDoc : type.DECIMAL(10, 6),
		IGVDoc 		: type.DECIMAL(10, 6),
		C048 		: type.DECIMAL(10, 6),
		Estado 		: type.TEXT,
		monto_autorizado 			: type.STRING,
		usuario_monto_autorizado 	: type.STRING,
		fecha_monto_autorizado 		: type.DATE,
		SubEstado 			: type.TEXT,
		FechaConformidad 	: type.DATE,
		ObsConformidad 		: type.TEXT,
		PersonalTecnico 	: type.TEXT,
		OTRealizada : type.TEXT,
		C055 		: type.TEXT,
		C056 		: type.TEXT,
		C057 		: type.TEXT,
		FichaInspeccion 	: type.TEXT,
		PropuestaTecnica 	: type.TEXT,
		DireccionFiscal 	: type.TEXT,
		NroAplicacion 	: type.STRING,
		Adicionales 	: type.INTEGER,
		IncMovilidad 	: type.INTEGER,
		Supervisor 		: type.INTEGER,
		NombreSupervisor: type.STRING,
		TipoServicio 	: type.STRING,// Saneamiento, SS.GG., Limpieza
		RUC 			: type.DOUBLE,
		Observaciones 	: type.TEXT,
		ClienteCert 	: type.STRING,
		LocalCert 		: type.STRING,
		DireccionCert 	: type.STRING,
		ClienteFact 	: type.STRING,
		NombreClienteFact 	: type.STRING,
		DireccionFact 		: type.STRING,
		FactCert 	: type.INTEGER,
		Servicio 	: type.INTEGER,
		nombre_sistema 		: type.STRING,
		nombre_servicio 	: type.STRING,
		Nota 			: type.TEXT,
		Volumen 		: type.INTEGER,
		AOtro 			: type.TEXT,
		CPOtro 			: type.TEXT,
		NomComercial 	: type.TEXT,
		Autorizado 		: type.INTEGER,
		Telefono 		: type.TEXT,
		DirEnv 		: type.STRING,
		ContEnv 	: type.STRING,
		FechaEnv 	: type.STRING,
		NotaFac1 	: type.TEXT,
		Urbanizacion : type.STRING,
		idUbigeo 		: type.STRING,
		ubigeo 			: type.STRING,
		emailCliente 	: type.STRING,
		permiso_adicionar 	: type.INTEGER,
		impreso 			: type.INTEGER,
		url_pdf 			: type.TEXT,
		modificado 			: type.STRING,
		nombre_supervisor 	: type.STRING,
		nPersonal 	: type.INTEGER,
		adjuntos 	: type.STRING,
		uu_id 		: type.STRING,
		IncNomComercial : type.INTEGER,
		id_empresa 	: type.INTEGER,
		empresa 	: type.STRING,
		deleted_at 	: type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}