// * DEPRECADO * => reqPersonalModel.js
module.exports = (sequelize, type) => {
	return sequelize.define('utb_reqpersonal',{
		IdReqPersonal:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: true
		},
		uu_id           : type.STRING,
        FechaEmision    : type.DATEONLY,
        cant_cubierta   : type.STRING,
		IdPuestoPersonal: type.INTEGER,
		Cantidad        : type.INTEGER,
		IdArea          : type.INTEGER,
        area            : type.STRING,
        JefeInmediato   : type.INTEGER,
        jefe_inmediato  : type.STRING,
        Motivo          : type.INTEGER,
        Tiempo          : type.STRING,
        Documentos      : type.STRING,
        Horario         : type.STRING,
        Salario         : type.STRING,
        Solicitante     : type.INTEGER,
        nombre_solicitante : type.STRING,
        Cliente         : type.INTEGER,
        nombre_cliente  : type.STRING,
        Sucursal        : type.INTEGER,
        nombre_sucursal : type.STRING,
        Conocimientos   : type.STRING,
        Estudios        : type.STRING,
        Experiencia     : type.STRING,
        CursosEspecializacion       : type.STRING,
        CaracteristicasPersonales   : type.STRING,
        Sexo                : type.STRING,
        Edad                : type.STRING,
        Habilidades         : type.STRING,
        FechaPresentacion   : type.STRING,
        UsuarioAprob    : type.STRING,
        FechaAprob      : type.DATE,
        Dias            : type.STRING,
        PuestoIso       : type.STRING,
        idPuestoIso     : type.INTEGER,
        Estado          : type.INTEGER,
        UsuarioCerrado  : type.STRING,
        FechaCerrado    : type.DATE,
        estado_reclutamiento : type.STRING,
        UsuarioMod      : type.STRING,
        FechaMod        : type.DATE,
        C031            : type.STRING,
        C032            : type.DATE,
        C033            : type.STRING,
        C034            : type.STRING,
        C035            : type.STRING,
        C036            : type.STRING,
        C037            : type.DATE,
        Glosa           : type.TEXT,
        C039            : type.STRING,
        C040            : type.STRING,
        Atendido        : type.INTEGER,
        Direccion       : type.STRING,
        Comentario      : type.STRING,
        Departamento    : type.STRING,
        Departamento_nombre : type.STRING,
        Provincia       : type.STRING,
        Provincia_nombre: type.STRING,
        IdDistrito      : type.STRING,
        distrito        : type.STRING,
        Distrito_nombre : type.STRING,
        FechaInicio     : type.DATE,
        PersAsignado    : type.STRING,
        ObsRequerimiento: type.STRING,
        dni_vigente         : type.STRING,
        cert_policial       : type.STRING,
        cert_domiciliario   : type.STRING,
        ant_penales         : type.STRING,
        carnet_sanidad      : type.STRING,
        cv_doc              : type.STRING,
        asignacion_familiar : type.STRING,
        verificativa        : type.STRING,
        recibo_servicios    : type.STRING,
        id_responsable      : type.INTEGER,
        responsable         : type.STRING,
        sol_emo             : type.STRING,
        uniforme            : type.TEXT,
        const_estudios      : type.STRING,
        estado_emo          : type.STRING,
        protocolo_industrial: type.STRING,
        bono_nocturno       : type.STRING,
        dec_domiciliario    : type.STRING,
        bonificacion        : type.STRING,
        fecha_emision_emo   : type.DATE,
        motivo_anulado      : type.TEXT,
        FechaAprobado       : type.DATE,
        UsuarioAprobado     : type.STRING,
        UsuarioAnulado      : type.STRING,
        FechaAnulado        : type.STRING,
        id_empresa          : type.INTEGER,
        empresa             : type.STRING,
        deleted_at          : type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}