
// reqMaterialesCabModel.js


module.exports = (sequelize, type) => {
	return sequelize.define('utb_requerimientoscab',{
		IdRequerimientoCab:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: false
		},
		uu_id       : type.STRING,
        Codigo      : type.STRING,
		IdClienteProv: type.DOUBLE,
		cliente     : type.STRING,
        IdSucursal  : type.INTEGER,
        sucursal    : type.TEXT,
        Fecha       : type.DATEONLY,
        MotivoTraslado  : type.TEXT,
        IdCentro        : type.INTEGER,
        centro_costos   : type.STRING,
        PersonalAsig    : type.TEXT,
        Glosa           : type.TEXT,
        DireccionPartida : type.TEXT,
        DireccionDestino : type.TEXT,
        C015            : type.STRING,
        C016            : type.STRING,
        TipoServicio    : type.STRING,
        UnidadNegocio   : type.STRING,
        C019            : type.INTEGER,
        MotivoAnulacion : type.TEXT,
        Atendido    : type.INTEGER,
        C022        : type.INTEGER,
        C023        : type.INTEGER,
        Estado      : type.STRING,
        UsuarioAprob : type.STRING,
        FechaMod    : type.DATE,
        UsuarioMod  : type.STRING,
        C041        : type.TEXT,
        MesCorrsp   : type.STRING,
        TipProducto : type.STRING,
        C044        : type.TEXT,
        NroOC       : type.TEXT,
        NroPC       : type.TEXT,
        C047        : type.TEXT,
        NroPA       : type.TEXT,
        NroPE       : type.TEXT,
        NroGuia     : type.TEXT,
        C051        : type.TEXT,
        UsuarioAut  : type.TEXT,
        AtendidoManual  : type.INTEGER,
        IdUbigeo        : type.STRING,
        Departamento    : type.STRING,
        Provincia       : type.STRING,
        Distrito        : type.STRING,
        C058            : type.TEXT,
        C059            : type.TEXT,
        C060            : type.TEXT,
        TROrigen        : type.INTEGER,
        TipoReq         : type.STRING,
        TipoDocOrigen   : type.STRING,
        NroDocOrigen    : type.STRING,
        MontoMax        : type.DECIMAL(10, 4),
        FechaEnt        : type.DATEONLY,
        UsuarioModAp    : type.STRING,
        FechaModAp      : type.DATEONLY,
        UsuarioModAn    : type.STRING,
        FechaModAn      : type.DATE,
        PC              : type.INTEGER,
        OC              : type.INTEGER,
        PE              : type.INTEGER,
        liberado        : type.INTEGER,
        flag            : type.STRING,
        porcentaje      : type.DECIMAL(10, 4),
        InEstructura    : type.STRING,
        NoInEstructura  : type.STRING,
        total_detalle   : type.STRING,
        items_detalle   : type.STRING,
        id_empresa      : type.STRING,
        empresa         : type.STRING,
        deleted_at      : type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}
