// sucursalModel.js
// sucursalModel
module.exports = (sequelize, type) => {
	return sequelize.define('utb_sucursales',{
		IdSucursal:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: false
		},
		uu_id           : type.STRING,
		Codigo 			: type.STRING,
		IdClienteProv 	: type.DOUBLE,
		nombre_cliente	: type.TEXT,
		Descripcion 	: type.TEXT,
		Pais 		: type.STRING,
		Departamento: type.STRING,
		NombreDepartamento : type.STRING,
		Provincia   : type.STRING,
		NombreProvincia : type.STRING,
        Distrito    : type.STRING,
		TipoDir     : type.STRING,
        NombreCalle : type.STRING,
        NroCalle    : type.STRING,
		OtrosCalle  : type.STRING,
		Direccion 		: type.TEXT,
		Referencia 		: type.TEXT,
		Telefono 		: type.TEXT,
		DiaEntregaReq 	: type.TEXT,
		C008 			: type.TEXT,
		Contacto 		: type.TEXT,
		persona_recepcion 	: type.STRING,
		MailContacto 		: type.STRING,
		C010 	: type.TEXT,
		Estado 	: type.INTEGER,
		Supervisor 		: type.TEXT,
		DiaAtencion 	: type.TEXT,
		NroPersonalAsig : type.TEXT,
		HorarioEntrega 	: type.TEXT,
		UsuarioMod 		: type.INTEGER,
		FechaMod 		: type.TEXT,
		NroVisitasXSup 	: type.TEXT,
		CoordOperaciones : type.TEXT,
		CoordComercial 	: type.TEXT,
		CoordPersonal 	: type.TEXT,
		NroVisitas 	: type.TEXT,
		Archivo 	: type.TEXT,
		MontoMax 	: type.DECIMAL(10, 2),
		C025 		: type.TEXT,
		IdUbigeo 	: type.STRING,
		ubigeo 		: type.TEXT,
		personal_destacado : type.TEXT,
		nro_super_manana   : type.INTEGER,
		nro_super_tarde    : type.INTEGER,
		nro_super_noche    : type.INTEGER,
		id_personal_destacado : type.INTEGER,
		Urbanizacion 			: type.TEXT,
		MontoImplementos 		: type.DECIMAL( 20, 2),
		MontoIndumentarias 		: type.DECIMAL( 20, 2),
		MontoLineaInstitucional : type.DECIMAL( 20, 2),
		ContactoOLI 	: type.STRING,
		MovilOLI 		: type.STRING,
		EmailOLI 		: type.STRING,
		UsuarioModOLI 	: type.STRING,
		FechaModOLI 	: type.DATE,
		ContactoOSA 	: type.STRING,
		MovilOSA 		: type.STRING,
		EmailOSA 		: type.STRING,
		UsuarioModOSA 	: type.STRING,
		FechaModOSA 	: type.DATE,
		lat : type.TEXT,
		lng : type.TEXT,
		IdConcar	: type.STRING,
		id_empresa  : type.INTEGER,
		empresa 	: type.TEXT,
		deleted_at 	: type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}