// utbClienteModel.js
module.exports = (sequelize, type) => {
	return sequelize.define('utb_clienteproveedor',{
		IdClienteProv:{
			type : type.INTEGER,
			primaryKey : true,
			autoIncrement: false
		},
		Tipo 		: type.INTEGER,
		rubro 		: type.STRING,
		tipo_cliente: type.STRING,
		id_rubro 	: type.INTEGER,
		Razon 		: type.TEXT,
		RUC 		: type.TEXT,
		Direccion 	: type.TEXT,
		ReferenciaDireccion : type.TEXT,
		IdMoneda 	: type.INTEGER,
		moneda 		: type.STRING,
		Telefono 	: type.TEXT,
		Estado 		: type.INTEGER,
		IdGrupo 	: type.INTEGER,
		Grupo 		: type.STRING,
		UsuarioMod 	: type.TEXT,
		FechaMod 	: type.DATE,
		Fax 		: type.INTEGER,
		Movil 		: type.INTEGER,
		Email 		: type.STRING,
		Contacto 	: type.INTEGER,
		Glosa 		: type.TEXT,
		IdGiro 		: type.INTEGER,
		nombre_giro : type.STRING,
		NombreComercial : type.TEXT,
		IdCentro 		: type.INTEGER,
		centro_costos 	: type.STRING,
		TipoServicio 	: type.TEXT,
		DiaDespacho 	: type.TEXT,
		ColaboradorAsig : type.TEXT,
		TipoCliente 	: type.TEXT,
		TerminosR 		: type.TEXT,
		MontoMaxReq 	: type.DECIMAL(10, 6),
		C025 			: type.TEXT,
		CondicionPago 	: type.INTEGER,
		CentroCosto 	: type.INTEGER,
		DNI 			: type.TEXT,
		VisitasProg 	: type.INTEGER,
		CarnetExt 		: type.TEXT,
		AgenteRet 		: type.STRING,
		Tipodocumento 	: type.STRING,
		Urbanizacion 	: type.STRING,
		idUbigeo 		: type.STRING,
		ubigeo 			: type.TEXT,
		Pais 			: type.STRING,
		Departamento 	: type.STRING,
		Provincia 		: type.STRING,
		Distrito 		: type.STRING,
		TipoDir 		: type.STRING,
		NombreCalle 	: type.STRING,
		NroCalle 		: type.STRING,
		OtrosCalle 			: type.STRING,
		EjecutivoCuentas 		: type.STRING,
		NombreEjecutivoCuentas 	: type.STRING,
		EjecutivoCuentas_OSA 	: type.STRING,
		NombreEjecutivoCuentas_OSA 	: type.STRING,
		EjecutivoCuentas_OLI 		: type.STRING,
		NombreEjecutivoCuentas_OLI 	: type.STRING,
		CodMoneda 		: type.STRING,
		NombreMoneda 	: type.STRING,
		EstadoDoc 		: type.STRING,
		ContactoOLI 	: type.STRING,
		MovilOLI 		: type.STRING,
		EmailOLI 		: type.STRING,
		monto_contrato 	: type.DECIMAL(10, 6),
		go 				: type.DECIMAL(10, 6),
		gad 			: type.DECIMAL(10, 6),
		ut 				: type.DECIMAL(10, 6),
		locales 		: type.INTEGER,
		vencimiento_contrato 	: type.DATEONLY,
		inicio_contrato 		: type.DATEONLY,
		operarios 				: type.INTEGER,
		UsuarioModOLI 			: type.STRING,
		FechaModOLI 			: type.DATE,
		ContactoOSA 	: type.STRING,
		MovilOSA 		: type.STRING,
		EmailOSA 		: type.STRING,
		UsuarioModOSA 	: type.STRING,
		FechaModOSA 	: type.DATE,
		llave 			: type.INTEGER,
		id_ejecutivo_cuenta_osa : type.INTEGER,
		ejecutivo_cuenta_osa 	: type.STRING,
		id_facturador 			: type.INTEGER,
		monto_materiales 	: type.DECIMAL(10, 6),
		monto_implementos 	: type.DECIMAL(10, 6),
		monto_indumentaria 	: type.DECIMAL(10, 6),
		monto_intitucional 	: type.DECIMAL(10, 6),
		id_ejecutivo_cuenta_oli : type.INTEGER,
		ejecutivo_cuenta 		: type.STRING,
		facturador 				: type.STRING,
		id_ejecutivo_cuenta 	: type.INTEGER,
		ejecutivo_cuenta_oli 	: type.INTEGER,
		lat 		: type.INTEGER,
		tags 		: type.INTEGER,
		lng 		: type.INTEGER,
		id_empresa 	: type.INTEGER,
		empresa 	: type.STRING,
		deleted_at 	: type.DATE,
		createdAt: {
			type: type.DATE,
			field: 'created_at',
		},
		updatedAt: {
			type: type.DATE,
			field: 'updated_at'
		}
	},{
		timestamps: true,
		freezeTableName: true
	})
}

